package com.hinsty.traffic.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.hinsty.traffic.service.object.TrafficData;
// KEEP INCLUDES END
/**
 * Entity mapped to table APP_DAY_TRAFFIC.
 */
public class AppDayTraffic {

    private String packageName;
    private Integer year;
    private Integer month;
    private Integer day;
    private String name;
    private Long rx;
    private Long tx;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AppDayTraffic() {
    }

    public AppDayTraffic(String packageName, Integer year, Integer month, Integer day, String name, Long rx, Long tx) {
        this.packageName = packageName;
        this.year = year;
        this.month = month;
        this.day = day;
        this.name = name;
        this.rx = rx;
        this.tx = tx;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getRx() {
        return rx;
    }

    public void setRx(Long rx) {
        this.rx = rx;
    }

    public Long getTx() {
        return tx;
    }

    public void setTx(Long tx) {
        this.tx = tx;
    }

    // KEEP METHODS - put your custom methods here

    public void add(long rx, long tx) {
        this.tx += tx;
        this.rx += rx;
    }

    public void add(TrafficData d){
        this.rx+=d.rx;
        this.tx+=d.tx;
    }

    public AppDayTraffic(String packageName, Integer year, Integer month, Integer day,
                         String name,TrafficData trafficData) {
        this.packageName = packageName;
        this.year = year;
        this.month = month;
        this.day = day;
        this.name = name;
        this.rx = trafficData.rx;
        this.tx = trafficData.tx;
    }
    // KEEP METHODS END

}
