package com.hinsty.traffic.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hinsty.traffic.dao.AppDayTraffic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table APP_DAY_TRAFFIC.
*/
public class AppDayTrafficDao extends AbstractDao<AppDayTraffic, Void> {

    public static final String TABLENAME = "APP_DAY_TRAFFIC";

    /**
     * Properties of entity AppDayTraffic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PackageName = new Property(0, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property Year = new Property(1, Integer.class, "year", false, "YEAR");
        public final static Property Month = new Property(2, Integer.class, "month", false, "MONTH");
        public final static Property Day = new Property(3, Integer.class, "day", false, "DAY");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Rx = new Property(5, Long.class, "rx", false, "RX");
        public final static Property Tx = new Property(6, Long.class, "tx", false, "TX");
    };


    public AppDayTrafficDao(DaoConfig config) {
        super(config);
    }
    
    public AppDayTrafficDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'APP_DAY_TRAFFIC' (" + //
                "'PACKAGE_NAME' TEXT," + // 0: packageName
                "'YEAR' INTEGER," + // 1: year
                "'MONTH' INTEGER," + // 2: month
                "'DAY' INTEGER," + // 3: day
                "'NAME' TEXT," + // 4: name
                "'RX' INTEGER," + // 5: rx
                "'TX' INTEGER);"); // 6: tx
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_APP_DAY_TRAFFIC_PACKAGE_NAME_YEAR_MONTH_DAY ON APP_DAY_TRAFFIC" +
                " (PACKAGE_NAME,YEAR,MONTH,DAY);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'APP_DAY_TRAFFIC'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AppDayTraffic entity) {
        stmt.clearBindings();
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(1, packageName);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(2, year);
        }
 
        Integer month = entity.getMonth();
        if (month != null) {
            stmt.bindLong(3, month);
        }
 
        Integer day = entity.getDay();
        if (day != null) {
            stmt.bindLong(4, day);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        Long rx = entity.getRx();
        if (rx != null) {
            stmt.bindLong(6, rx);
        }
 
        Long tx = entity.getTx();
        if (tx != null) {
            stmt.bindLong(7, tx);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public AppDayTraffic readEntity(Cursor cursor, int offset) {
        AppDayTraffic entity = new AppDayTraffic( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // packageName
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // year
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // month
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // day
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // rx
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // tx
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AppDayTraffic entity, int offset) {
        entity.setPackageName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setYear(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setMonth(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDay(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRx(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setTx(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(AppDayTraffic entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(AppDayTraffic entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
