package com.hinsty.traffic.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hinsty.traffic.dao.Traffic;
import com.hinsty.traffic.dao.AppDayTraffic;

import com.hinsty.traffic.dao.TrafficDao;
import com.hinsty.traffic.dao.AppDayTrafficDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trafficDaoConfig;
    private final DaoConfig appDayTrafficDaoConfig;

    private final TrafficDao trafficDao;
    private final AppDayTrafficDao appDayTrafficDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trafficDaoConfig = daoConfigMap.get(TrafficDao.class).clone();
        trafficDaoConfig.initIdentityScope(type);

        appDayTrafficDaoConfig = daoConfigMap.get(AppDayTrafficDao.class).clone();
        appDayTrafficDaoConfig.initIdentityScope(type);

        trafficDao = new TrafficDao(trafficDaoConfig, this);
        appDayTrafficDao = new AppDayTrafficDao(appDayTrafficDaoConfig, this);

        registerDao(Traffic.class, trafficDao);
        registerDao(AppDayTraffic.class, appDayTrafficDao);
    }
    
    public void clear() {
        trafficDaoConfig.getIdentityScope().clear();
        appDayTrafficDaoConfig.getIdentityScope().clear();
    }

    public TrafficDao getTrafficDao() {
        return trafficDao;
    }

    public AppDayTrafficDao getAppDayTrafficDao() {
        return appDayTrafficDao;
    }

}
