package com.hinsty.traffic.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.hinsty.traffic.service.object.TrafficData;
// KEEP INCLUDES END
/**
 * Entity mapped to table TRAFFIC.
 */
public class Traffic {

    private Integer year;
    private Integer month;
    private Integer day;
    private Long rx;
    private Long tx;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Traffic() {
    }

    public Traffic(Integer year, Integer month, Integer day, Long rx, Long tx) {
        this.year = year;
        this.month = month;
        this.day = day;
        this.rx = rx;
        this.tx = tx;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public Long getRx() {
        return rx;
    }

    public void setRx(Long rx) {
        this.rx = rx;
    }

    public Long getTx() {
        return tx;
    }

    public void setTx(Long tx) {
        this.tx = tx;
    }

    // KEEP METHODS - put your custom methods here

    public void add(TrafficData d){
        this.tx+=d.tx;
        this.rx+=d.rx;
    }
    public void add(long rx,long tx){
        this.tx+=tx;
        this.rx+=rx;
    }
    public void set(long rx,long tx){
        this.tx=tx;
        this.rx=rx;
    }
    // KEEP METHODS END

}
